name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "App Version: $VERSION"

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/Aplikasiku-${{ env.VERSION }}.apk

      - name: Update Version to API
        run: |
          curl -X POST "${{ secrets.API_URL }}/api/version/update" \
          -H "Content-Type: application/json" \
          -d '{"platform":"android", "version":"${{ env.VERSION }}"}'

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: aplikasiku-apk
          path: build/app/outputs/flutter-apk/Aplikasiku-${{ env.VERSION }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          files: build/app/outputs/flutter-apk/Aplikasiku-${{ env.VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
